In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('Advertising.csv')

In [5]:
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [6]:
X=df.drop('sales',axis=1)
y=df['sales']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [7]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [8]:
from sklearn.linear_model import ElasticNet

In [9]:
help(ElasticNet)

Help on class ElasticNet in module sklearn.linear_model._coordinate_descent:

class ElasticNet(sklearn.base.MultiOutputMixin, sklearn.base.RegressorMixin, sklearn.linear_model._base.LinearModel)
 |  ElasticNet(
 |      alpha=1.0,
 |      *,
 |      l1_ratio=0.5,
 |      fit_intercept=True,
 |      precompute=False,
 |      max_iter=1000,
 |      copy_X=True,
 |      tol=0.0001,
 |      warm_start=False,
 |      positive=False,
 |      random_state=None,
 |      selection='cyclic'
 |  )
 |
 |  Linear regression with combined L1 and L2 priors as regularizer.
 |
 |  Minimizes the objective function::
 |
 |          1 / (2 * n_samples) * ||y - Xw||^2_2
 |          + alpha * l1_ratio * ||w||_1
 |          + 0.5 * alpha * (1 - l1_ratio) * ||w||^2_2
 |
 |  If you are interested in controlling the L1 and L2 penalty
 |  separately, keep in mind that this is equivalent to::
 |
 |          a * ||w||_1 + 0.5 * b * ||w||_2^2
 |
 |  where::
 |
 |          alpha = a + b and l1_ratio = a / (a + b)
 |
 |  The parameter l1_ratio corresponds to alpha in the glmnet R package while
 |  alpha corresponds to the lambda parameter in glmnet. Specifically, l1_ratio
 |  = 1 is the lasso penalty. Currently, l1_ratio <= 0.01 is not reliable,
 |  unless you supply your own sequence of alpha.
 |
 |  Read more in the :ref:`User Guide <elastic_net>`.
 |
 |  Parameters
 |  ----------
 |  alpha : float, default=1.0
 |      Constant that multiplies the penalty terms. Defaults to 1.0.
 |      See the notes for the exact mathematical meaning of this
 |      parameter. ``alpha = 0`` is equivalent to an ordinary least square,
 |      solved by the :class:`LinearRegression` object. For numerical
 |      reasons, using ``alpha = 0`` with the ``Lasso`` object is not advised.
 |      Given this, you should use the :class:`LinearRegression` object.
 |
 |  l1_ratio : float, default=0.5
 |      The ElasticNet mixing parameter, with ``0 <= l1_ratio <= 1``. For
 |      ``l1_ratio = 0`` the penalty is an L2 penalty. ``For l1_ratio = 1`` it
 |      is an L1 penalty.  For ``0 < l1_ratio < 1``, the penalty is a
 |      combination of L1 and L2.
 |
 |  fit_intercept : bool, default=True
 |      Whether the intercept should be estimated or not. If ``False``, the
 |      data is assumed to be already centered.
 |
 |  precompute : bool or array-like of shape (n_features, n_features),                 default=False
 |      Whether to use a precomputed Gram matrix to speed up
 |      calculations. The Gram matrix can also be passed as argument.
 |      For sparse input this option is always ``False`` to preserve sparsity.
 |      Check :ref:`an example on how to use a precomputed Gram Matrix in ElasticNet
 |      <sphx_glr_auto_examples_linear_model_plot_elastic_net_precomputed_gram_matrix_with_weighted_samples.py>`
 |      for details.
 |
 |  max_iter : int, default=1000
 |      The maximum number of iterations.
 |
 |  copy_X : bool, default=True
 |      If ``True``, X will be copied; else, it may be overwritten.
 |
 |  tol : float, default=1e-4
 |      The tolerance for the optimization: if the updates are
 |      smaller than ``tol``, the optimization code checks the
 |      dual gap for optimality and continues until it is smaller
 |      than ``tol``, see Notes below.
 |
 |  warm_start : bool, default=False
 |      When set to ``True``, reuse the solution of the previous call to fit as
 |      initialization, otherwise, just erase the previous solution.
 |      See :term:`the Glossary <warm_start>`.
 |
 |  positive : bool, default=False
 |      When set to ``True``, forces the coefficients to be positive.
 |
 |  random_state : int, RandomState instance, default=None
 |      The seed of the pseudo random number generator that selects a random
 |      feature to update. Used when ``selection`` == 'random'.
 |      Pass an int for reproducible output across multiple function calls.
 |      See :term:`Glossary <random_state>`.
 |
 |  selection : {'cyclic', 'random'}, default='cyclic'
 |      If set to 'random', a random coefficient is updated every iteration
 |      rather than looping over features sequentially by default. This
 |      (setting to 'random') often leads to significantly faster convergence
 |      especially when tol is higher than 1e-4.
 |
 |  Attributes
 |  ----------
 |  coef_ : ndarray of shape (n_features,) or (n_targets, n_features)
 |      Parameter vector (w in the cost function formula).
 |
 |  sparse_coef_ : sparse matrix of shape (n_features,) or             (n_targets, n_features)
 |      Sparse representation of the `coef_`.
 |
 |  intercept_ : float or ndarray of shape (n_targets,)
 |      Independent term in decision function.
 |
 |  n_iter_ : list of int
 |      Number of iterations run by the coordinate descent solver to reach
 |      the specified tolerance.
 |
 |  dual_gap_ : float or ndarray of shape (n_targets,)
 |      Given param alpha, the dual gaps at the end of the optimization,
 |      same shape as each observation of y.
 |
 |  n_features_in_ : int
 |      Number of features seen during :term:`fit`.
 |
 |      .. versionadded:: 0.24
 |
 |  feature_names_in_ : ndarray of shape (`n_features_in_`,)
 |      Names of features seen during :term:`fit`. Defined only when `X`
 |      has feature names that are all strings.
 |
 |      .. versionadded:: 1.0
 |
 |  See Also
 |  --------
 |  ElasticNetCV : Elastic net model with best model selection by
 |      cross-validation.
 |  SGDRegressor : Implements elastic net regression with incremental training.
 |  SGDClassifier : Implements logistic regression with elastic net penalty
 |      (``SGDClassifier(loss="log_loss", penalty="elasticnet")``).
 |
 |  Notes
 |  -----
 |  To avoid unnecessary memory duplication the X argument of the fit method
 |  should be directly passed as a Fortran-contiguous numpy array.
 |
 |  The precise stopping criteria based on `tol` are the following: First, check that
 |  that maximum coordinate update, i.e. :math:`\max_j |w_j^{new} - w_j^{old}|`
 |  is smaller than `tol` times the maximum absolute coefficient, :math:`\max_j |w_j|`.
 |  If so, then additionally check whether the dual gap is smaller than `tol` times
 |  :math:`||y||_2^2 / n_{      ext{samples}}`.
 |
 |  Examples
 |  --------
 |  >>> from sklearn.linear_model import ElasticNet
 |  >>> from sklearn.datasets import make_regression
 |
 |  >>> X, y = make_regression(n_features=2, random_state=0)
 |  >>> regr = ElasticNet(random_state=0)
 |  >>> regr.fit(X, y)
 |  ElasticNet(random_state=0)
 |  >>> print(regr.coef_)
 |  [18.83816048 64.55968825]
 |  >>> print(regr.intercept_)
 |  1.451
 |  >>> print(regr.predict([[0, 0]]))
 |  [1.451]
 |
 |  -   :ref:`sphx_glr_auto_examples_linear_model_plot_lasso_and_elasticnet.py`
 |      showcases ElasticNet alongside Lasso and ARD Regression for sparse
 |      signal recovery in the presence of noise and feature correlation.
 |
 |  Method resolution order:
 |      ElasticNet
 |      sklearn.base.MultiOutputMixin
 |      sklearn.base.RegressorMixin
 |      sklearn.linear_model._base.LinearModel
 |      sklearn.base.BaseEstimator
 |      sklearn.utils._repr_html.base.ReprHTMLMixin
 |      sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
 |      sklearn.utils._metadata_requests._MetadataRequester
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(
 |      self,
 |      alpha=1.0,
 |      *,
 |      l1_ratio=0.5,
 |      fit_intercept=True,
 |      precompute=False,
 |      max_iter=1000,
 |      copy_X=True,
 |      tol=0.0001,
 |      warm_start=False,
 |      positive=False,
 |      random_state=None,
 |      selection='cyclic'
 |  )
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __sklearn_tags__(self)
 |
 |  fit(self, X, y, sample_weight=None, check_input=True)
 |      Fit model with coordinate descent.
 |
 |      Parameters
 |      ----------
 |      X : {ndarray, sparse matrix, sparse array} of (n_samples, n_features)
 |          Data.
 |
 |          Note that large sparse matrices and arrays requiring `int64`
 |          indices are not accepted.
 |
 |      y : ndarray of shape (n_samples,) or (n_samples, n_targets)
 |          Target. Will be cast to X's dtype if necessary.
 |
 |      sample_weight : float or array-like of shape (n_samples,), default=None
 |          Sample weights. Internally, the `sample_weight` vector will be
 |          rescaled to sum to `n_samples`.
 |
 |          .. versionadded:: 0.23
 |
 |      check_input : bool, default=True
 |          Allow to bypass several input checking.
 |          Don't use this parameter unless you know what you do.
 |
 |      Returns
 |      -------
 |      self : object
 |          Fitted estimator.
 |
 |      Notes
 |      -----
 |      Coordinate descent is an algorithm that considers each column of
 |      data at a time hence it will automatically convert the X input
 |      as a Fortran-contiguous numpy array if necessary.
 |
 |      To avoid memory re-allocation it is advised to allocate the
 |      initial data in memory directly using that format.
 |
 |  set_fit_request(
 |      self: sklearn.linear_model._coordinate_descent.ElasticNet,
 |      *,
 |      sample_weight: Union[bool, NoneType, str] = '$UNCHANGED$'
 |  ) -> sklearn.linear_model._coordinate_descent.ElasticNet from sklearn.utils._metadata_requests.RequestMethod.__get__.<locals>
 |      Configure whether metadata should be requested to be passed to the ``fit`` method.
 |
 |              Note that this method is only relevant when this estimator is used as a
 |              sub-estimator within a :term:`meta-estimator` and metadata routing is enabled
 |              with ``enable_metadata_routing=True`` (see :func:`sklearn.set_config`).
 |              Please check the :ref:`User Guide <metadata_routing>` on how the routing
 |              mechanism works.
 |
 |              The options for each parameter are:
 |
 |              - ``True``: metadata is requested, and passed to ``fit`` if provided. The request is ignored if metadata is not provided.
 |
 |              - ``False``: metadata is not requested and the meta-estimator will not pass it to ``fit``.
 |
 |              - ``None``: metadata is not requested, and the meta-estimator will raise an error if the user provides it.
 |
 |              - ``str``: metadata should be passed to the meta-estimator with this given alias instead of the original name.
 |
 |              The default (``sklearn.utils.metadata_routing.UNCHANGED``) retains the
 |              existing request. This allows you to change the request for some
 |              parameters and not others.
 |
 |              .. versionadded:: 1.3
 |
 |              Parameters
 |              ----------
 |              sample_weight : str, True, False, or None,                     default=sklearn.utils.metadata_routing.UNCHANGED
 |                  Metadata routing for ``sample_weight`` parameter in ``fit``.
 |
 |              Returns
 |              -------
 |              self : object
 |                  The updated object.
 |
 |  set_score_request(
 |      self: sklearn.linear_model._coordinate_descent.ElasticNet,
 |      *,
 |      sample_weight: Union[bool, NoneType, str] = '$UNCHANGED$'
 |  ) -> sklearn.linear_model._coordinate_descent.ElasticNet from sklearn.utils._metadata_requests.RequestMethod.__get__.<locals>
 |      Configure whether metadata should be requested to be passed to the ``score`` method.
 |
 |              Note that this method is only relevant when this estimator is used as a
 |              sub-estimator within a :term:`meta-estimator` and metadata routing is enabled
 |              with ``enable_metadata_routing=True`` (see :func:`sklearn.set_config`).
 |              Please check the :ref:`User Guide <metadata_routing>` on how the routing
 |              mechanism works.
 |
 |              The options for each parameter are:
 |
 |              - ``True``: metadata is requested, and passed to ``score`` if provided. The request is ignored if metadata is not provided.
 |
 |              - ``False``: metadata is not requested and the meta-estimator will not pass it to ``score``.
 |
 |              - ``None``: metadata is not requested, and the meta-estimator will raise an error if the user provides it.
 |
 |              - ``str``: metadata should be passed to the meta-estimator with this given alias instead of the original name.
 |
 |              The default (``sklearn.utils.metadata_routing.UNCHANGED``) retains the
 |              existing request. This allows you to change the request for some
 |              parameters and not others.
 |
 |              .. versionadded:: 1.3
 |
 |              Parameters
 |              ----------
 |              sample_weight : str, True, False, or None,                     default=sklearn.utils.metadata_routing.UNCHANGED
 |                  Metadata routing for ``sample_weight`` parameter in ``score``.
 |
 |              Returns
 |              -------
 |              self : object
 |                  The updated object.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  path = enet_path(
 |      X,
 |      y,
 |      *,
 |      l1_ratio=0.5,
 |      eps=0.001,
 |      n_alphas=100,
 |      alphas=None,
 |      precompute='auto',
 |      Xy=None,
 |      copy_X=True,
 |      coef_init=None,
 |      verbose=False,
 |      return_n_iter=False,
 |      positive=False,
 |      check_input=True,
 |      **params
 |  ) from sklearn.linear_model._coordinate_descent
 |      Compute elastic net path with coordinate descent.
 |
 |      The elastic net optimization function varies for mono and multi-outputs.
 |
 |      For mono-output tasks it is::
 |
 |          1 / (2 * n_samples) * ||y - Xw||^2_2
 |          + alpha * l1_ratio * ||w||_1
 |          + 0.5 * alpha * (1 - l1_ratio) * ||w||^2_2
 |
 |      For multi-output tasks it is::
 |
 |          (1 / (2 * n_samples)) * ||Y - XW||_Fro^2
 |          + alpha * l1_ratio * ||W||_21
 |          + 0.5 * alpha * (1 - l1_ratio) * ||W||_Fro^2
 |
 |      Where::
 |
 |          ||W||_21 = \sum_i \sqrt{\sum_j w_{ij}^2}
 |
 |      i.e. the sum of norm of each row.
 |
 |      Read more in the :ref:`User Guide <elastic_net>`.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          Training data. Pass directly as Fortran-contiguous data to avoid
 |          unnecessary memory duplication. If ``y`` is mono-output then ``X``
 |          can be sparse.
 |
 |      y : {array-like, sparse matrix} of shape (n_samples,) or         (n_samples, n_targets)
 |          Target values.
 |
 |      l1_ratio : float, default=0.5
 |          Number between 0 and 1 passed to elastic net (scaling between
 |          l1 and l2 penalties). ``l1_ratio=1`` corresponds to the Lasso.
 |
 |      eps : float, default=1e-3
 |          Length of the path. ``eps=1e-3`` means that
 |          ``alpha_min / alpha_max = 1e-3``.
 |
 |      n_alphas : int, default=100
 |          Number of alphas along the regularization path.
 |
 |      alphas : array-like, default=None
 |          List of alphas where to compute the models.
 |          If None alphas are set automatically.
 |
 |      precompute : 'auto', bool or array-like of shape             (n_features, n_features), default='auto'
 |          Whether to use a precomputed Gram matrix to speed up
 |          calculations. If set to ``'auto'`` let us decide. The Gram
 |          matrix can also be passed as argument.
 |
 |      Xy : array-like of shape (n_features,) or (n_features, n_targets),         default=None
 |          Xy = np.dot(X.T, y) that can be precomputed. It is useful
 |          only when the Gram matrix is precomputed.
 |
 |      copy_X : bool, default=True
 |          If ``True``, X will be copied; else, it may be overwritten.
 |
 |      coef_init : array-like of shape (n_features, ), default=None
 |          The initial values of the coefficients.
 |
 |      verbose : bool or int, default=False
 |          Amount of verbosity.
 |
 |      return_n_iter : bool, default=False
 |          Whether to return the number of iterations or not.
 |
 |      positive : bool, default=False
 |          If set to True, forces coefficients to be positive.
 |          (Only allowed when ``y.ndim == 1``).
 |
 |      check_input : bool, default=True
 |          If set to False, the input validation checks are skipped (including the
 |          Gram matrix when provided). It is assumed that they are handled
 |          by the caller.
 |
 |      **params : kwargs
 |          Keyword arguments passed to the coordinate descent solver.
 |
 |      Returns
 |      -------
 |      alphas : ndarray of shape (n_alphas,)
 |          The alphas along the path where models are computed.
 |
 |      coefs : ndarray of shape (n_features, n_alphas) or             (n_targets, n_features, n_alphas)
 |          Coefficients along the path.
 |
 |      dual_gaps : ndarray of shape (n_alphas,)
 |          The dual gaps at the end of the optimization for each alpha.
 |
 |      n_iters : list of int
 |          The number of iterations taken by the coordinate descent optimizer to
 |          reach the specified tolerance for each alpha.
 |          (Is returned when ``return_n_iter`` is set to True).
 |
 |      See Also
 |      --------
 |      MultiTaskElasticNet : Multi-task ElasticNet model trained with L1/L2 mixed-norm     as regularizer.
 |      MultiTaskElasticNetCV : Multi-task L1/L2 ElasticNet with built-in cross-validation.
 |      ElasticNet : Linear regression with combined L1 and L2 priors as regularizer.
 |      ElasticNetCV : Elastic Net model with iterative fitting along a regularization path.
 |
 |      Notes
 |      -----
 |      For an example, see
 |      :ref:`examples/linear_model/plot_lasso_lasso_lars_elasticnet_path.py
 |      <sphx_glr_auto_examples_linear_model_plot_lasso_lasso_lars_elasticnet_path.py>`.
 |
 |      Examples
 |      --------
 |      >>> from sklearn.linear_model import enet_path
 |      >>> from sklearn.datasets import make_regression
 |      >>> X, y, true_coef = make_regression(
 |      ...    n_samples=100, n_features=5, n_informative=2, coef=True, random_state=0
 |      ... )
 |      >>> true_coef
 |      array([ 0.        ,  0.        ,  0.        , 97.9, 45.7])
 |      >>> alphas, estimated_coef, _ = enet_path(X, y, n_alphas=3)
 |      >>> alphas.shape
 |      (3,)
 |      >>> estimated_coef
 |       array([[ 0.,  0.787,  0.568],
 |              [ 0.,  1.120,  0.620],
 |              [-0., -2.129, -1.128],
 |              [ 0., 23.046, 88.939],
 |              [ 0., 10.637, 41.566]])
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties defined here:
 |
 |  sparse_coef_
 |      Sparse representation of the fitted `coef_`.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __abstractmethods__ = frozenset()
 |
 |  __annotations__ = {'_parameter_constraints': <class 'dict'>}
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from sklearn.base.MultiOutputMixin:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.RegressorMixin:
 |
 |  score(self, X, y, sample_weight=None)
 |      Return :ref:`coefficient of determination <r2_score>` on test data.
 |
 |      The coefficient of determination, :math:`R^2`, is defined as
 |      :math:`(1 - \frac{u}{v})`, where :math:`u` is the residual
 |      sum of squares ``((y_true - y_pred)** 2).sum()`` and :math:`v`
 |      is the total sum of squares ``((y_true - y_true.mean()) ** 2).sum()``.

In [ ]:
base_elastic_net_model=ElasticNet()

In [11]:
param_grid={'alpha':[0.1,1,5,10,50,100],'l1_ratio':[.1,.5,.7,.95,.99,1]}

In [13]:
from sklearn.model_selection import GridSearchCV

In [14]:
grid = GridSearchCV(
    estimator=base_elastic_net_model,
    param_grid=param_grid,
    cv=5,
    scoring='neg_mean_squared_error',
    verbose=2
)

In [16]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.99; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.99; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.99; total time=   0.0s
[CV] END ................................alpha=5, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=5, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=5, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=5, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=5, l1_ratio=1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.99; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.99; total time=   0.0s
[CV] END ...............................alpha=50, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=50, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=50, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=50, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=50, l1_ratio=1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.99; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s

GridSearchCV(cv=5, estimator=ElasticNet(),
             param_grid={'alpha': [0.1, 1, 5, 10, 50, 100],
                         'l1_ratio': [0.1, 0.5, 0.7, 0.95, 0.99, 1]},
             scoring='neg_mean_squared_error', verbose=2)

In [17]:
grid.best_estimator_

ElasticNet(alpha=0.1, l1_ratio=1)

In [19]:
grid.best_params_

{'alpha': 0.1, 'l1_ratio': 1}

In [21]:
pd.DataFrame(grid.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_l1_ratio,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004495,0.004379,0.001552,0.000869,0.1,0.10,"{'alpha': 0.1, 'l1_ratio': 0.1}",-2.920581,-1.842830,-2.856136,-2.259857,-4.834877,-2.942856,1.026090,6
1,0.001496,0.000315,0.001115,0.000525,0.1,0.50,"{'alpha': 0.1, 'l1_ratio': 0.5}",-2.777186,-1.804157,-2.716130,-2.177455,-4.856587,-2.866303,1.057770,5
2,0.001085,0.000134,0.000501,0.000027,0.1,0.70,"{'alpha': 0.1, 'l1_ratio': 0.7}",-2.714707,-1.751083,-2.651177,-2.146936,-4.862003,-2.825181,1.077481,4
3,0.001035,0.000197,0.000542,0.000094,0.1,0.95,"{'alpha': 0.1, 'l1_ratio': 0.95}",-2.647940,-1.681851,-2.575967,-2.121031,-4.845926,-2.774543,1.092442,3
4,0.001053,0.000126,0.000782,0.000249,0.1,0.99,"{'alpha': 0.1, 'l1_ratio': 0.99}",-2.638619,-1.671496,-2.564636,-2.118303,-4.844056,-2.767422,1.094763,2
5,0.002186,0.000425,0.001040,0.000503,0.1,1.00,"{'alpha': 0.1, 'l1_ratio': 1}",-2.636353,-1.668940,-2.561837,-2.117687,-4.843620,-2.765687,1.095340,1
6,0.001581,0.000638,0.000720,0.000271,1.0,0.10,"{'alpha': 1, 'l1_ratio': 0.1}",-6.991133,-7.448907,-9.369970,-8.638205,-8.399568,-8.169557,0.851063,12
7,0.001609,0.000263,0.000958,0.000216,1.0,0.50,"{'alpha': 1, 'l1_ratio': 0.5}",-5.427932,-6.576176,-8.251353,-7.346804,-7.544802,-7.029414,0.962254,11
8,0.001133,0.000261,0.000536,0.000033,1.0,0.70,"{'alpha': 1, 'l1_ratio': 0.7}",-4.430697,-5.697066,-7.477012,-6.400177,-6.960888,-6.193168,1.061407,10
9,0.001371,0.000295,0.000981,0.000431,1.0,0.95,"{'alpha': 1, 'l1_ratio': 0.95}",-3.400345,-4.350250,-6.266280,-4.881958,-6.060222,-4.991811,1.069785,9
10,0.001329,0.000193,0.000724,0.000183,1.0,0.99,"{'alpha': 1, 'l1_ratio': 0.99}",-3.255067,-4.107170,-6.052372,-4.611446,-5.903893,-4.785989,1.066623,8
11,0.002433,0.000326,0.001556,0.000724,1.0,1.00,"{'alpha': 1, 'l1_ratio': 1}",-3.218819,-4.045254,-5.998185,-4.542843,-5.864437,-4.733908,1.066090,7
12,0.003381,0.000993,0.001496,0.000174,5.0,0.10,"{'alpha': 5, 'l1_ratio': 0.1}",-15.400429,-19.529658,-22.096982,-23.185472,-17.084852,-19.459479,2.931181,13
13,0.003915,0.000586,0.001895,0.000496,5.0,0.50,"{'alpha': 5, 'l1_ratio': 0.5}",-17.316360,-22.889445,-26.382490,-28.176217,-19.253643,-22.803631,4.108353,14
14,0.003704,0.001015,0.001685,0.000583,5.0,0.70,"{'alpha': 5, 'l1_ratio': 0.7}",-19.942711,-26.168882,-28.678293,-31.267956,-21.673803,-25.546329,4.226838,16
15,0.003154,0.001285,0.001378,0.000450,5.0,0.95,"{'alpha': 5, 'l1_ratio': 0.95}",-21.195523,-27.088074,-29.992533,-32.035562,-23.017156,-26.665769,4.082067,17
16,0.001497,0.000420,0.000824,0.000326,5.0,0.99,"{'alpha': 5, 'l1_ratio': 0.99}",-21.195523,-27.088074,-29.992533,-32.035562,-23.017156,-26.665769,4.082067,17
17,0.001840,0.000303,0.001175,0.000168,5.0,1.00,"{'alpha': 5, 'l1_ratio': 1}",-21.195523,-27.088074,-29.992533,-32.035562,-23.017156,-26.665769,4.082067,17
18,0.002067,0.000344,0.001061,0.000180,10.0,0.10,"{'alpha': 10, 'l1_ratio': 0.1}",-18.263365,-23.519902,-26.307808,-27.986196,-20.091561,-23.233766,3.652274,15
19,0.001718,0.000600,0.000805,0.000178,10.0,0.50,"{'alpha': 10, 'l1_ratio': 0.5}",-21.195523,-27.088074,-29.992533,-32.035562,-23.017156,-26.665769,4.082067,17
20,0.001913,0.000160,0.001148,0.000106,10.0,0.70,"{'alpha': 10, 'l1_ratio': 0.7}",-21.195523,-27.088074,-29.992533,-32.035562,-23.017156,-26.665769,4.082067,17
21,0.001962,0.000735,0.001077,0.000858,10.0,0.95,"{'alpha': 10, 'l1_ratio': 0.95}",-21.195523,-27.088074,-29.992533,-32.035562,-23.017156,-26.665769,4.082067,17
22,0.001348,0.000344,0.000621,0.000116,10.0,0.99,"{'alpha': 10, 'l1_ratio': 0.99}",-21.195523,-27.088074,-29.992533,-32.035562,-23.017156,-26.665769,4.082067,17
23,0.001481,0.000444,0.001042,0.000339,10.0,1.00,"{'alpha': 10, 'l1_ratio': 1}",-21.195523,-27.088074,-29.992533,-32.035562,-23.017156,-26.665769,4.082067,17
24,0.002842,0.000921,0.001187,0.000104,50.0,0.10,"{'alpha': 50, 'l1_ratio': 0.1}",-21.195523,-27.088074,-29.992533,-32.035562,-23.017156,-26.665769,4.082067,17
25,0.002742,0.000901,0.001341,0.000367,50.0,0.50,"{'alpha': 50, 'l1_ratio': 0.5}",-21.195523,-27.088074,-29.992533,-32.035562,-23.017156,-26.665769,4.082067,17
26,0.003170,0.001258,0.001746,0.000601,50.0,0.70,"{'alpha': 50, 'l1_ratio': 0.7}",-21.195523,-27.088074,-29.992533,-32.035562,-23.017156,-26.665769,4.082067,17
27,0.002462,0.000212,0.001341,0.000131,50.0,0.95,"{'alpha': 50, 'l1_ratio': 0.95}",-21.195523,-27.088074,-29.992533,-32.035562,-23.017156,-26.665769,4.082067,17
28,0.002559,0.000462,0.001487,0.000353,50.0,0.99,"{'alpha': 50, 'l1_ratio': 0.99}",-21.195523,-27.088074,-29.992533,-32.035562,-23.017156,-26.665769,4.082067,17
29,0.002865,0.000309,0.001596,0.000436,50.0,1.00,"{'alpha': 50, 'l1_ratio': 1}",-21.195523,-27.088074,-29.992533,-32.035562,-23.017156,-26.665769,4.082067,17
30,0.003356,0.000540,0.001936,0.000575,100.0,0.10,"{'alpha': 100, 'l1_ratio': 0.1}",-21.195523,-27.088074,-29.992533,-32.035562,-23.017156,-26.665769,4.082067,17
31,0.002413,0.000183,0.001347,0.000257,100.0,0.50,"{'alpha': 100, 'l1_ratio': 0.5}",-21.195523,-27.088074,-29.992533,-32.035562,-23.017156,-26.665769,4.082067,17
32,0.002814,0.000384,0.001407,0.000195,100.0,0.70,"{'alpha': 100, 'l1_ratio': 0.7}",-21.195523,-27.088074,-29.992533,-32.035562,-23.017156,-26.665769,4.082067,17
33,0.003036,0.000739,0.001529,0.000497,100.0,0.95,"{'alpha': 100, 'l1_ratio': 0.95}",-21.195523,-27.088074,-29.992533,-32.035562,-23.017156,-26.665769,4.082067,17
34,0.002766,0.000595,0.001399,0.000151,100.0,0.99,"{'alpha': 100, 'l1_ratio': 0.99}",-21.195523,-27.088074,-29.992533,-32.035562,-23.017156,-26.665769,4.082067,17
35,0.002993,0.000665,0.001468,0.000324,100.0,1.00,"{'alpha': 100, 'l1_ratio': 1}",-21.195523,-27.088074,-29.992533,-32.035562,-23.017156,-26.665769,4.082067,17

In [22]:
y_pred=grid.predict(X_test)

In [23]:
from sklearn.metrics import mean_squared_error

In [24]:
mean_squared_error(y_test,y_pred)

3.696337740547821